name: TahoeLab
favicon: null
layout_spectrum: 0.11861
typography_spectrum: 0.28116
title: TahoeLab Skis and Snowboards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46018582-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#314359'
    - '#7993ac'
    - '#f8f8f8'
    - '#bec2cb'
    - '#080607'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
