name: TahoeLab
favicon: null
layout_spectrum: 0.18165
typography_spectrum: 0.28116
title: TahoeLab -Handmade Skis and Snowboards
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46018582-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#314357'
    - '#5e6776'
    - '#7993ac'
    - '#f8f8f8'
    - '#181818'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
